Home task01
algorithms-club/algorithms-normatov pull request #1
Opened 2017-03-31 08:39 UTC by vnormatov

2017-04-05 20:22 UTC, PavelMelnyk commented
Description very general
you should describe in pull request what functionality you added
mention what it should solve/do

### Example

Added methods for solving tasks
- watermelon
- nextYearFind
- tests for methods

2017-04-07 14:08 UTC, pavlom0x requested changes

2017-04-07 14:08 UTC, pavlom0x commented on entry-test/beautifulyear.js
> +'use strick';
`'use strict'` check all files

2017-04-07 15:06 UTC, vnormatov commented on entry-test/beautifulyear.js
> +'use strick';
ok))

2017-04-07 16:13 UTC, pavlom0x requested changes

2017-04-07 16:13 UTC, pavlom0x commented on entry-test/watermelon.js
> +        return "NO"
better to use single quote `'`

2017-04-07 16:13 UTC, pavlom0x commented on entry-test/watermelon.js
> +    else return 'YES';
don't mix `'` and `"`

2017-04-07 16:13 UTC, pavlom0x commented on entry-test/watermelon.js
> +function makeDecisionType(weight) {
what's a difference with `makeDecision` ?

2017-04-07 16:13 UTC, pavlom0x commented on entry-test/stones.js
> +function getMinStonesToDell(numberOfStones, line) {
`numberOfStones` not used
do you actually need it?

2017-04-07 16:13 UTC, PavelMelnyk commented on test/stones-spec.js
> +        let quantity = algolib.stones.getMinStonesToDell(2, 'BRBG');
description collision

2017-04-07 16:13 UTC, PavelMelnyk commented on test/watermelon-spec.js
> +    it('make decision if weight is even', function () {
How is this case different with previous one?

2017-04-07 21:14 UTC, yuchiko requested changes

2017-04-07 21:14 UTC, yuchiko commented on entry-test/chat.js
> +function isSucceessSayHello(phrase) {
typo in function name `isSucceessSayHello` should be `isSuccessSayHello`

2017-04-07 21:14 UTC, yuchiko commented on entry-test/beautifulyear.js
> +            return i;
bad naming, it will be good if you will use something like `nextYear` not `i`

2017-04-07 21:14 UTC, yuchiko commented on entry-test/chat.js
> +    for (let obj of phraseArray) {
`obj` ?

2017-04-07 21:14 UTC, yuchiko commented on entry-test/chat.js
> +                if (!result.localeCompare('h'))
`localeCompare` is redundant here, it's enough to use equal compare
`result === 'h'` same to other cases

2017-04-09 09:35 UTC, vnormatov commented on entry-test/watermelon.js
> +function makeDecisionType(weight) {
I did it only for me, to understand how "module.exports" works

2017-04-09 10:13 UTC, vnormatov commented on test/watermelon-spec.js
> +    it('make decision if weight is even', function () {
I checked range limits of input values, odd and even numbers. Previous is a limit of input range.

2017-04-09 10:20 UTC, vnormatov commented on entry-test/watermelon.js
> +    else return 'YES';
fixed

2017-04-09 10:20 UTC, vnormatov commented on test/stones-spec.js
> +        let quantity = algolib.stones.getMinStonesToDell(2, 'BRBG');
fixed

2017-04-09 10:21 UTC, vnormatov commented on entry-test/chat.js
> +    for (let obj of phraseArray) {
fixed

2017-04-09 10:21 UTC, vnormatov commented on entry-test/chat.js
> +                if (!result.localeCompare('h'))
fixed

2017-04-09 10:21 UTC, vnormatov commented on entry-test/beautifulyear.js
> +            return i;
fixed

2017-04-18 17:31 UTC, pavlom0x approved these changes

2017-04-18 17:32 UTC, yuchiko approved these changes

2017-04-18 17:35 UTC, merged