Dynamic connection problem
algorithms-club/algorithms-normatov pull request #2
Opened 2017-04-02 18:33 UTC by vnormatov

2017-04-07 16:38 UTC, pavlom0x requested changes
plz remove redundant empty line

2017-04-07 16:38 UTC, PavelMelnyk commented on unionFind.js
> +        this._elements[b] = isNaN(this._elements[b]) ? b : this._elements[b];
it will be better if we check `a` and `b` at the same way

2017-04-07 16:38 UTC, PavelMelnyk commented on unionFind.js
> +
trailing empty line

2017-04-07 16:38 UTC, PavelMelnyk commented on unionFind.js
> +        return count;
you can return `components.length` and remove this variable

2017-04-07 16:38 UTC, PavelMelnyk commented on unionFind.js
> +                if (isUnique(components, this._elements[i])) {
`isUnique` can be replaced with `indexOf`

2017-04-07 16:38 UTC, PavelMelnyk commented on test/unioonFind.spec.js
> +    it('should #component return component name', function () {
test description should be unique

2017-04-07 16:38 UTC, PavelMelnyk commented on test/unioonFind.spec.js
> +    it('should #count return number of components if we have 3 components', function () {
#count should return number not only when we have 3 components

2017-04-09 10:25 UTC, vnormatov commented on unionFind.js
> +        this._elements[b] = isNaN(this._elements[b]) ? b : this._elements[b];
ok, I did it for me to better remember the syntax)

2017-04-09 10:35 UTC, vnormatov commented on unionFind.js
> +        return count;
fixed

2017-04-09 10:35 UTC, vnormatov commented on unionFind.js
> +                if (isUnique(components, this._elements[i])) {
fixed

2017-04-09 10:35 UTC, vnormatov commented on unionFind.js
> +
ok)

2017-04-09 10:41 UTC, vnormatov commented on test/unioonFind.spec.js
> +    it('should #component return component name', function () {
fixed

2017-04-09 10:41 UTC, vnormatov commented on test/unioonFind.spec.js
> +    it('should #count return number of components if we have 3 components', function () {
ok)

2017-04-17 20:19 UTC, pavlom0x approved these changes
good work

2017-05-03 18:41 UTC, PavelMelnyk commented
if nothing to add than merge it

2017-05-03 18:51 UTC, merged