Quick union
algorithms-club/algorithms-normatov pull request #5
Opened 2017-04-10 20:06 UTC by vnormatov

2017-04-17 20:17 UTC, pavlom0x approved these changes

2017-04-17 20:17 UTC, PavelMelnyk commented on test/quickUnion.spec.js
> +     })
something with indentation

2017-04-17 21:21 UTC, pavlom0x requested changes

2017-04-17 21:21 UTC, pavlom0x commented on QuickUnion.js
> +        if (isNaN(this._numberElementsInComponent[rootA])) this._numberElementsInComponent[rootA] = a;
at the beginning `_numberElementsInComponent` of each element is equal to 1 but not to the index of that element

2017-04-17 21:21 UTC, pavlom0x commented on QuickUnion.js
> +        for (var nextElement = 0; nextElement < this._elements.length; nextElement++) {
maybe it's not `nextElement` but `currentElement` ?

2017-04-17 21:21 UTC, PavelMelnyk commented on QuickUnion.js
> +     findRoot(arrayOfelements[element], arrayOfelements);
you forgot to return the result of recursive function

`return findRoot(arr..`

2017-04-17 21:21 UTC, PavelMelnyk commented on QuickUnion.js
> +        if (isNaN(this._numberElementsInComponent[rootA])) this._numberElementsInComponent[rootA] = a;
do you have tests that check this behavior?

the smaler tree should connect to bigger one

2017-04-20 11:37 UTC, vnormatov commented on test/quickUnion.spec.js
> +     })
fixed

2017-04-20 11:57 UTC, vnormatov commented on QuickUnion.js
> +        if (isNaN(this._numberElementsInComponent[rootA])) this._numberElementsInComponent[rootA] = a;
fixed

2017-04-20 11:57 UTC, vnormatov commented on QuickUnion.js
> +        for (var nextElement = 0; nextElement < this._elements.length; nextElement++) {
fixed

2017-04-20 12:03 UTC, vnormatov commented on QuickUnion.js
> +     findRoot(arrayOfelements[element], arrayOfelements);
thank you)))

2017-05-03 18:40 UTC, PavelMelnyk commented
good job!
merge it

2017-05-03 18:41 UTC, pavlom0x approved these changes

2017-05-03 18:42 UTC, merged