List
algorithms-club/algorithms-normatov pull request #6
Opened 2017-04-24 13:48 UTC by vnormatov

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica requested changes
Еще есть над чем работать.

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on LinkedList.js
>          this._elements['value'] = value;
Массивы в JS, конечно, всё выдержат, но именованные аргументы лучше применимы к объектам, а не к массивами.

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on LinkedList.js
> +        this.lastElement;
Эти свойства приватные или должны быть доступными из вне?
Если первое, то приватные свойства именуются как `this._prop`

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on LinkedList.js
> +            elementOfList = new ElementOfList(element, this.lastElement);
Название значения элемента `element` путает. Стоило бы, всё же, назвать её `value`

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on LinkedList.js
>          this._elements = [];
Ты подписал свойство, как приватное, а далее в коде обращаешься к нему напрямую. Бардак. Так нельзя. Если свойство приватное, значит обращаться к нему можно только изнутри класса.

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on LinkedList.js
>              throw  new Error("List is empty");
Стоит ли сообщать пользователю о том, что список пуст, в столь грубой форме?
На практике выброс ошибки вызовет краш в коде, а это не есть гуд.

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on LinkedList.js
> +        this.lastElement = this.lastElement._elements['previous'];
Не пойму зачем такая длинная колбаса. `previous`, `next` и `value` можно было загнать в объект `{ }`, который уже присвоить к `this.lastElement.` Тогда бы вышло короче и лаконичнее - `this.lastElement.previous`

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on test/list-spec.js
> +    it('#unshift 3 elements from list', function () {
А на выброс ошибки забыл проверить?

2017-04-24 20:19 UTC, Eugene-Musika-cpamatica commented on test/list-spec.js
> -    /* it('#unshift 3 elements from list', function () {
При проверке конкретного теста, не нужно комментировать все остальные. Достаточно к целевому тесту дописать `.only`. Например `it.only(...`, `describe.only(...`
Остальные тесты тогда будут игнорироваться

2017-04-24 20:28 UTC, Eugene-Musika-cpamatica reviewed
Это не очень круто, когда во время проверки прилетает новый коммит и ты понимаешь, что часть твоих замечаний уже не актуальна.

2017-04-25 07:51 UTC, vnormatov commented on LinkedList.js
>          this._elements = [];
исправил

2017-04-25 07:51 UTC, vnormatov commented on LinkedList.js
>          this._elements['value'] = value;
Массивы в js насколько я знаю являются обьектами. typeof возвращает object для массивов.

2017-04-25 07:51 UTC, vnormatov commented on LinkedList.js
> +        this.lastElement;
Приватное, исправил.

2017-04-25 07:52 UTC, vnormatov commented on LinkedList.js
> +            elementOfList = new ElementOfList(element, this.lastElement);
Нужно быть храбрее) Исправил.

2017-04-25 07:52 UTC, vnormatov commented on LinkedList.js
>              throw  new Error("List is empty");
Хотел посмотреть как mocha ловит исключения, а на практике это проблема клиентского кода, который не использует try catch. Этот момент в описании к классу обозначен.

2017-04-25 07:53 UTC, vnormatov commented on LinkedList.js
> +        this.lastElement = this.lastElement._elements['previous'];
можно) но я только осваиваю js и в этом классе хотел попробовать ассоциативные массивы

2017-04-25 07:53 UTC, vnormatov commented on test/list-spec.js
> -    /* it('#unshift 3 elements from list', function () {
ок

2017-04-25 07:54 UTC, vnormatov commented on test/list-spec.js
> +    it('#unshift 3 elements from list', function () {
забыл

2017-04-25 07:55 UTC, vnormatov commented
Согласен, на то мы и учимся)

2017-04-25 17:27 UTC, Eugene-Musika-cpamatica commented on methods/LinkedList/LinkedListObject.js
> +            elementOfList = new LinkedListObject(value, value);
Уоу. О_о. Не нужно создавать вселенные внутри вселенных. Ты чего? Оставь список и элемент отдельными классами.

2017-04-25 19:11 UTC, vnormatov commented on methods/LinkedList/LinkedListObject.js
> +            elementOfList = new LinkedListObject(value, value);
По хорошему каждый класс - отдельный файл

2017-04-26 22:21 UTC, YuriiHoliuk requested changes
так як ти не знав до того js то дуже добре)
реалізація там де масив в цілому мені більше сподобалась, але обов'язково треба або масив на об'єкт змінити або замість value & prev використати 0 і 1. Тому і не апрувлю.
P.S. помилки створювати то плюс, але не знаю чи там конкретно вона умісна, треба запитатись

2017-04-26 22:21 UTC, YuriiHoliuk commented on methods/LinkedList/LinkedListArray.js
> +            elementOfList = new ElementOfList(value, value);
два рази value не потрібно передавати, можеж передати null/undefined, або всередині класу перевірку зробити чи передано другий аргумент

2017-04-26 22:21 UTC, YuriiHoliuk commented on methods/LinkedList/LinkedListArray.js
> +        this.elements['previous'] = previous;
це бед практіс, бо ти створив масив і використовуєш його як об'єкт

2017-04-26 22:21 UTC, YuriiHoliuk commented on methods/LinkedList/LinkedListObject.js
> +            elementOfList = new LinkedListObject(value, value);
взагалі тут виходить, що ти кожного разу створюєш цілий новий список, а не елемент. чи я щось не так зрозумів?

2017-04-26 22:21 UTC, YuriiHoliuk commented on methods/queue/Queue.js
> +        this._queue = new linkedList;
після конструктора треба дужки
і конструктор прийнято писати з великої

2017-04-26 22:21 UTC, YuriiHoliuk commented on test/LinkedListArray-spec.js
> +        });
ці тести можна напевне було узагальнити

2017-04-26 22:21 UTC, YuriiHoliuk commented on test/LinkedListObject-spec.js
> +
класно, що 2 реалізації мають однаковий інтерфейс

2017-04-27 06:42 UTC, vnormatov commented on methods/LinkedList/LinkedListObject.js
> +            elementOfList = new LinkedListObject(value, value);
тут создается обьект `LinkedListObject` который является елементом списка.

2017-04-27 06:47 UTC, vnormatov commented on methods/LinkedList/LinkedListArray.js
> +        this.elements['previous'] = previous;
Мне кажется, более интуитивно понятно исппользовать ассоциативные массивы, вместо обычных. Пойди разберись что имел ввиду автор под `this.elements[0]` и `this.elements[1]`. В дальнейшем, конечно, в таких случаях буду использовать обьекты.

2017-04-27 06:49 UTC, vnormatov commented on methods/LinkedList/LinkedListArray.js
> +            elementOfList = new ElementOfList(value, value);
Что б не проверять клиентский код на правильность входных данных, я сделал такую типа оптимизацию) Меньше проверок/кода - легче воспринимать.

2017-04-27 07:02 UTC, vnormatov commented on methods/queue/Queue.js
> +        this._queue = new linkedList;
По поводу скобок, я ж в `this._queue = new linkedList;` вроде как обращаюсь к переменной в которую выще подключил класс. Или я как то не так понимаю этот процесс? По поводу с большой буквы интересно, не знал) В java конструкторы тоже с большой буквы пишутся, но они повторяют имя класса. например тут бы было 
`Queue(){
this._queue = new linkedList;}
`

2017-04-27 07:03 UTC, vnormatov commented on test/LinkedListArray-spec.js
> +        });
во время разработки лист неправильно работал более чем с 2 элементами, вот этот тест и остался тут по историческим причинам)

2017-04-27 14:20 UTC, YuriiHoliuk commented on methods/LinkedList/LinkedListArray.js
> +        this.elements['previous'] = previous;
об'єкт по суті і є асоціативним масивом

2017-04-27 14:23 UTC, YuriiHoliuk commented on methods/LinkedList/LinkedListArray.js
> +            elementOfList = new ElementOfList(value, value);
не дуже то і легше, я довго старався вшарити для чого це + якщо дані це гігантські строки то це займе більше пам'яті

я вів до того, що в джс жодні аргументи не є обов'язковими і можна взагалі нічого не передавати

2017-04-27 14:27 UTC, YuriiHoliuk commented on methods/LinkedList/LinkedListObject.js
> +            elementOfList = new LinkedListObject(value, value);
а для чого тоді в LinkedListObject this._firstElemenеt,  this._lastElement?

2017-04-27 14:28 UTC, YuriiHoliuk commented on methods/queue/Queue.js
> +        this._queue = new linkedList;
та ніби все так
взагалі напевне через наслідування і розширення класу треба робити

2017-04-27 14:29 UTC, vnormatov commented
в каждом элементе списка есть инфа о первом и последнем элементе, хоть это
и избыточно)

On Thu, Apr 27, 2017 at 5:27 PM, Yurii Holiuk <notifications@github.com>
wrote:

> *@YuriiHoliuk* commented on this pull request.
> ------------------------------
>
> In methods/LinkedList/LinkedListObject.js
> <https://github.com/algorithms-club/algorithms-normatov/pull/6#discussion_r113709486>
> :
>
> > +class LinkedListObject {
> +
> +    constructor(value, previous) {
> +        this._firstElement;
> +        this._lastElement;
> +        this._element = {
> +            value: value,
> +            previous: previous,
> +            next: 'undefined'
> +        };
> +    }
> +
> +    push(value) {
> +        let elementOfList;
> +        if (this._firstElement=== undefined) {
> +            elementOfList = new LinkedListObject(value, value);
>
> а для чого тоді в LinkedListObject this._firstElemenеt, this._lastElement?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/algorithms-club/algorithms-normatov/pull/6#discussion_r113709486>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARTo89RQz2jUS-0XXI8I6AaHfWKwsgUcks5r0KXFgaJpZM4NGL-n>
> .
>

2017-05-03 18:44 UTC, PavelMelnyk commented
You have conflict here, resolve it 
Merge if work is finished

2017-05-03 18:54 UTC, merged